server.port: 8091

spring:
  redis:
    #数据库索引
    database: 9
    host: 192.168.197.128
    port: 6379
    jedis:
      pool:
        #最大连接数
        max-active: 200
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 10
        #最小空闲
        min-idle: 0
    #连接超时时间
    timeout: 10000
